# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

monitor=,preferred,auto,1,transform, 0
monitor = DP-3, preferred, 0x0, auto
monitor = HDMI-A-1, preferred, -1080x-650, auto, transform, 1

general {
    # Gaps and border
    gaps_in = 1
    gaps_out = 2
}

decoration {
    rounding = 22
    dim_special = 0.5
}

input {
    kb_layout = us
    kb_layout = us,us
    kb_variant = ,intl
    kb_options = grp:ctrl_space_toggle

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    force_no_accel = 1
    accel_profile = flat
}

