# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above



unbind = Super, Super_L
unbind = Super, Super_R
unbind = Super, catchall, global
unbind = Ctrl, Super_L, global
unbind = Ctrl, Super_R, global
# unbind = Super, mouse:272, global
# unbind = Super, mouse:273, global
# unbind = Super, mouse:274, global
# unbind = Super, mouse:275, global
# unbind = Super, mouse:276, global
# unbind = Super, mouse:277, global
unbind = Super, mouse_up,  global
unbind = Super, mouse_down,global

bindd = Super, Space, Toggle overview, global, quickshell:searchToggleRelease # [hidden] Toggle overview/launcher


unbind = Super, Tab,

unbind = Alt, F4
unbind = Super, Q
bindd = Alt, F4, Toggle session menu, global, quickshell:sessionToggle # Toggle session menu
bind = Super+Shift, Q, killactive, # Close

unbind = Super+Alt, Space
unbind = Super, S
bind = Super, S, togglefloating, # Float/Tile


#/# bind = Super+Shift, Hash,, # Send to workspace # (1, 2, 3,...)
bind = Super+Shift, 1, movetoworkspace, 1 # [hidden]
bind = Super+Shift, 2, movetoworkspace, 2 # [hidden]
bind = Super+Shift, 3, movetoworkspace, 3 # [hidden]
bind = Super+Shift, 4, movetoworkspace, 4 # [hidden]
bind = Super+Shift, 5, movetoworkspace, 5 # [hidden]
bind = Super+Shift, 6, movetoworkspace, 6 # [hidden]
bind = Super+Shift, 7, movetoworkspace, 7 # [hidden]
bind = Super+Shift, 8, movetoworkspace, 8 # [hidden]
bind = Super+Shift, 9, movetoworkspace, 9 # [hidden]
bind = Super+Shift, 0, movetoworkspace, 10 # [hidden]

bind = Super+Shift, grave, movetoworkspacesilent, special # Send to scratchpad



unbind = Super, code:11
unbind = Super, code:12
unbind = Super, code:13
unbind = Super, code:14
unbind = Super, code:15
unbind = Super, code:16
unbind = Super, code:17
unbind = Super, code:18
unbind = Super, code:19
unbind = Super, code:10


bind = Super, code:10, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 1 # [hidden]
bind = Super, code:11, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 2 # [hidden]
bind = Super, code:12, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 3 # [hidden]
bind = Super, code:13, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 4 # [hidden]
bind = Super, code:14, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 5 # [hidden]
bind = Super, code:15, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 6 # [hidden]
bind = Super, code:16, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 7 # [hidden]
bind = Super, code:17, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 8 # [hidden]
bind = Super, code:18, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 9 # [hidden]
bind = Super, code:19, exec, ~/.config/hypr/custom/scripts/hypr_move_show_workspace_clean.sh 10 # [hidden]





unbind = Super+Alt, S
unbind = Ctrl+Super, S

bind = Super, grave, togglespecialworkspace, # Toggle scratchpad
