# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrulev2 = workspace 10, class:^(spotify)$
windowrulev2 = workspace 6, class:^(discord)$

# ######## Workspace rules ########
workspace = special:special, gapsout:60
# windowrulev2 = opacity 0.9, onworkspace:special:special
